#----------------------------------------------#
# make tutorial zip file                       #
#----------------------------------------------#

cwd = `pwd`

zip: 
	@rm -f tutorial1.zip 
	@zip tutorial1.zip ../../doc/ProteinMechanicaTutorial1.pdf  *.pmc *.pdb *.pm 


