
SHELL = /usr/bin/sh

include gr_src.mk


# define include dirs
#--------------------
glut_inc = -I../../free_glut/freeglut_MinGW//include/GL
glut_inc = -I../../free_glut/freeglut_MinGW//include
#glut_inc = -I/usr/include/GL//include
gr_inc =  -I/usr/include/GL/include -I/usr/X11R6/include/
jpg_inc = ../jpg/include
inc = -I.  -I../../include \
           -I../include \
           -I../../common/include \

hdr = ../include/pm/gr/
common_dir = ../../common/src/
common_objs = $(common_dir)/common.o $(common_dir)/mth.o

# special cywin flags for my pos computer
#----------------------------------------
#cwf = -DUSE_CYGWIN_SPECIAL_HEADERS
wflags = -mno-cygwin  -DWIN32 

# use for debug: code crashes with -g -funroll-loops -march=pentium4 -mfpmath=sse
#copt = -g
#flags = $(inc) $(copt)  $(cwf)

# use for optimized execution 
copt = -O2 -pedantic
copt = -O2 
#flags = $(inc) $(cwf) $(copt) -funroll-loops -march=pentium4 -mfpmath=sse
flags = -DFREEGLUT_STATIC $(inc) $(copt)  $(cwf) $(wflags)

obj: $(obj) 

.cpp.o: 
	g++ $(flags) $(gr_inc) -c $<

win_glut.o: win_glut.cpp  win_glut.h
	g++ $(flags) $(glut_inc) -c $<

clean:
	rm -f *.o;

