#----------------------------------------------#
# make tutorial zip file                       #
#----------------------------------------------#

cwd = `pwd`

zip: 
	@rm -f tutorial2.zip 
	@zip tutorial2.zip ../../doc/ProteinMechanicaTutorial2.pdf  *.pmc *.pdb *.pm 


