#----------------------------------------------#
# make tutorial zip file                       #
#----------------------------------------------#

cwd = `pwd`

zip: 
	@rm -f tutorial3.zip 
	@zip tutorial3.zip ../../doc/ProteinMechanicaTutorial3.pdf  *.pmc *.pdb *.pm 


