#---------------------------------------------------------#
#                makefile for linux                       #
#---------------------------------------------------------#
SHELL = /usr/bin/sh

# sources 
#--------
include pm_src.mk

# ode path
#---------
ode_path = /usr/local/
ode_inc = $(ode_path)/include/

# define include dirs
#--------------------
glut_inc = -I/usr/include/w32api
opengl_inc = -I/usr/X11R6/include/  -I/usr/include/w32api
gr_inc = $(glut_inc) $(opengl_inc)

inc = -I.                    \
      -I $(ode_inc)          \
      -I../../gr++/include   \
      -I../include/          \
      -I../../common/include/ 

copt = -O2
flags = $(inc) $(copt) -DUSE_GRAPHICS 

obj: $(obj)

.cpp.o: 
	g++ $(flags) -c $<

clean:
	rm -f *.o;

