#----------------------------------------------#
# make tutorial zip file                       #
#----------------------------------------------#

cwd = `pwd`

zip: 
	@rm -f tutorial4.zip 
	@zip tutorial4.zip ../../doc/ProteinMechanicaTutorial4.pdf  *.pmc *.pdb *.pm 


